#ifndef ATRAIL_VERIFY
#define ATRAIL_VERIFY

/*
 * Atrail_verify.cpp
 *
 *  Created on: Jul 17, 2013
 *  Author: Abdulmelik Mohammed
 *  Verifies that an edge trail generated by an Atrail_search is in fact an A-trail with respect to the embedding given as an edge code.
 *  Argument 1: the edge code file.
 *  Argument 2: the edge trail file.
 */

#include <iostream>
#include <vector>
#include <list>
#include <iterator>
#include <string>
#include <sstream>
#include <fstream>
#include <stdio.h>
#include "ply_to_dimacs/boost_graph_helper.hpp"

// For console output to GUI
// not a good solution but it works
#include "vhelix.h"

namespace atrail_verify {
	
    int main(int argc, const char* argv[], vHelix &parent);
	// Reads the edge trail in the file input_filename and outputs the resulting trail in the list structure.
	bool read_trail(std::string input_filename, std::list<std::size_t> & trail, vHelix &parent);

	// Checks whether the trail trail_edgelist is an A-trail with respect to the embedding given by the edge code.
	// Precondition: The edge code is a valid embedding of a graph. The trail edgelist is a sequence of edge indices (unsigned integers from 0 to m-1)
	bool Atrail_verify(const std::vector<std::vector<std::size_t> > & edge_code,  const std::list<std::size_t> & trail_edgelist, vHelix &parent);
}

#endif
